### ISSUE TITLE
No module named request

### ISSUE THREAD

**Issue by mdavis-xyz** [flavio-fernandes/opencontrail-dev-centos7#1]
When I get to the second last command, I see:

```
$ python ./third_party/fetch_packages.py ; echo $?
```
```
Traceback (most recent call last):
  File "./third_party/fetch_packages.py", line 17, in <module>
    import urllib.request
ImportError: No module named request
1
```

I have tried `sudo yum install python-requests`. That didn't fix it.

`sudo easy_install -U requests` ([SO link](https://stackoverflow.com/questions/17309288/importerror-no-module-named-requests)) didn't either.

I want to try installing the requests library with `pip`, but `yum install python-pip` fails, even though I have the epel repo enabled.

**Comment by flavio-fernandes** [comment]
Heh, sorry but it has been 4 years since I touched this repo and I completely lost track of opencontrial.
I think the vagrant box has been updated to use python 3 and the scripts are so old they don't support it.
I recommend you contact the opencontrial folks directly:
http://www.opencontrail.org/newsletter-and-mailing-lists/

My apologies for the headache.
